In [6]:
import pandas as pd


df = pd.read_csv('Lending_club_clean.csv', nrows=200000)

In [7]:
df.shape

(200000, 89)

In [9]:
df.to_csv('Lending_club_clean_200k.csv', index=False)

In [10]:
df.head()

,Unnamed: 0,acc_open_past_24mths,addr_state,all_util,annual_inc,annual_inc_joint,application_type,avg_cur_bal,bc_open_to_buy,bc_util,...,term,tot_coll_amt,tot_hi_cred_lim,total_acc,total_bc_limit,total_cu_tl,total_il_high_credit_limit,total_rev_hi_lim,verification_status,loan_status
0,0,3.0,OK,58.0,50000.0,5693.51,Individual,3869.0,384.0,23.2,...,36 months,0.0,33430.0,18.0,500.0,0.0,27820.0,500.0,Verified,Current
1,1,15.0,FL,51.0,196000.0,5693.51,Individual,31468.0,7368.0,74.1,...,36 months,0.0,605228.0,53.0,28500.0,1.0,147178.0,52400.0,Source Verified,Current
2,2,5.0,NH,84.0,44000.0,81000.00,Joint App,8397.0,632.0,66.7,...,60 months,0.0,80367.0,14.0,1900.0,1.0,74167.0,6200.0,Not Verified,Current
3,3,2.0,AL,90.0,65000.0,5693.51,Individual,10685.0,63.0,98.1,...,60 months,0.0,101234.0,16.0,3300.0,3.0,10220.0,8800.0,Source Verified,Current
4,4,3.0,WA,1.0,52000.0,5693.51,Individual,25099.0,30359.0,0.5,...,36 months,0.0,191216.0,30.0,30500.0,2.0,0.0,31000.0,Source Verified,Fully Paid